name: 提取内核偏移量

on:
  workflow_dispatch

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install vmlinux-to-elf

    - name: 提取偏移量
      run: |
        python3 auto_extract_offsets.py boot.img -o . --device blazer --target-name target --keep-intermediate
        cp target/target.h ./target.h

    - name: 上传结果
      uses: actions/upload-artifact@v4
      with:
        name: target-h
        path: target.h
        if-no-files-found: error
